version: '2'
services:
  apache1:
    scale: 1
    start_on_create: true
  apache2:
    scale: 1
    start_on_create: true
  load-balancer:
    scale: 1
    lb_config:
      port_rules:
      - source_port: 80
        target_port: 80
        service: apache1
      - source_port: 80
        target_port: 80
        service: apache2
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
    start_on_create: true
